# Generated by Django 4.1.7 on 2023-03-07 01:19

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("population", models.IntegerField()),
                ("median_age", models.IntegerField()),
                ("land_area", models.IntegerField()),
                ("fertility_rate", models.FloatField()),
            ],
            bases=(core.mixins.DefaultModelMixin, models.Model),
        ),
    ]
