# Generated by Django 4.1.7 on 2023-03-07 11:21

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="continent",
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinces",
                        to="countries.country",
                    ),
                ),
            ],
            bases=(core.mixins.DefaultModelMixin, models.Model),
        ),
    ]
