# Generated by Django 4.1.7 on 2023-03-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_country_continent_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="median_age",
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="province",
            name="population",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
